# Generated by Django 3.1.5 on 2021-02-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20210125_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('moderation', 'на модерации'), ('published', 'опубликован'), ('rejected', 'отклоненный')], max_length=100),
        ),
    ]
