# Generated by Django 3.1.5 on 2021-01-12 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_reviews', '0002_review_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='content',
            new_name='text',
        ),
    ]
