# Generated by Django 3.1.5 on 2021-01-15 19:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_reviews', '0008_auto_20210115_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 15, 19, 53, 39, 859378, tzinfo=utc), null=True),
        ),
    ]
