# Generated by Django 3.1.5 on 2021-01-28 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'cart', 'verbose_name_plural': 'carts'},
        ),
    ]
