# Generated by Django 3.1.5 on 2021-02-01 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20210128_2021'),
        ('carts', '0002_auto_20210128_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(through='carts.CartItem', to='items.Item'),
        ),
    ]
